spring:
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://13.209.218.52:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
##    username: root
##    password: hello
##  jpa:
##   open-in-view: true
##    hibernate:
##      ddl-auto: create

springdoc:
  swagger-ui:
    path: /docs/swagger